language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"

before_install:
 #- pip insall id3reader==1.53.20070415
 #- pip install docopt==0.6.1
 - pip install nose==1.3.0
 - pip install coverage==3.6

before_script:
 - python setup.py install

script:
 - nosetests -v --with-coverage --cover-package=pymo
